spring:
  application:
    name: "DBTest"

# newjwtsecurity
# dbtest
  datasource:
    url: "jdbc:postgresql://localhost:5432/dbtest2"
    username: "postgres"
    password: "postgres"

  jpa:
#    show-sql: true
    open-in-view: false
    hibernate:
#      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        order_updates: true
        order_inserts: true
        jdbc:
          batch_size: 50
